In [1]:
import pandas as pd 
df = pd.read_csv("Indian_Kids_Screen_Time.csv")
df.head()

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban

In [2]:
df.isnull().sum()

Age                                     0
Gender                                  0
Avg_Daily_Screen_Time_hr                0
Primary_Device                          0
Exceeded_Recommended_Limit              0
Educational_to_Recreational_Ratio       0
Health_Impacts                       3218
Urban_or_Rural                          0
dtype: int64

In [14]:
df.duplicated().sum()
df[df.duplicated()]

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
996,16,Female,4.42,Laptop,True,0.35,"Poor Sleep, Anxiety",Urban
1700,9,Female,0.00,Smartphone,False,0.60,NaN,Urban
2090,10,Female,0.00,Tablet,False,0.49,NaN,Urban
3089,16,Male,4.81,Smartphone,True,0.31,NaN,Urban
3213,8,Female,4.84,Smartphone,True,0.46,Poor Sleep,Rural
3308,8,Female,0.00,Smartphone,False,0.53,NaN,Urban
3572,8,Male,0.00,Smartphone,False,0.41,NaN,Urban
4166,8,Female,0.00,Smartphone,False,0.47,NaN,Urban
4460,8,Female,0.00,Smartphone,False,0.47,NaN,Urban
4960,10,Female,0.00,Smartphone,False,0.55,NaN,Urban
5070,8,Female,0.00,Smartphone,False,0.59,NaN,Urban
5073,9,Female,0.00,TV,False,0.58,NaN,Urban
5291,8,Female,0.00,Smartphone,False,0.49,NaN,Urban
5892,11,Male,3.86,TV,True,0.30,Poor Sleep,Urban
6041,11,Female,3.20,Smartphone,True,0.35,Poor Sleep,Urban
6046,10,Male,0.00,Smartphone,False,0.45,NaN,Urban
6175,9,Female,0.00,Smartphone,False,0.59,NaN,Urban
6422,9,Male,0.00,Smartphone,False,0.41,NaN,Urban
6880,17,Female,4.93,Laptop,True,0.46,NaN,Urban
6927,9,Female,0.00,Smartphone,False,0.49,NaN,Urban
7018,10,Female,0.00,Smartphone,False,0.48,NaN,Urban
7103,9,Male,0.00,Tablet,False,0.50,NaN,Urban
7219,9,Female,0.00,Smartphone,False,0.48,NaN,Urban
7265,10,Female,0.00,TV,False,0.47,NaN,Rural
7633,10,Female,0.00,Tablet,False,0.49,NaN,Urban
7720,11,Female,2.74,Smartphone,False,0.47,NaN,Rural
7839,8,Female,0.00,Smartphone,False,0.44,NaN,Urban
7945,10,Male,0.00,Smartphone,False,0.50,NaN,Urban
8045,10,Female,0.00,Smartphone,False,0.56,NaN,Urban
8075,14,Male,4.94,Smartphone,True,0.41,NaN,Urban
8127,9,Male,0.00,Smartphone,False,0.41,NaN,Urban
8264,10,Male,0.00,Tablet,False,0.54,NaN,Urban
8297,8,Female,0.00,Smartphone,False,0.47,NaN,Urban
8829,9,Male,0.00,TV,False,0.47,NaN,Urban
8896,8,Female,0.00,TV,False,0.40,NaN,Urban
8932,8,Female,1.82,Tablet,False,0.43,NaN,Urban
8991,10,Female,1.07,TV,False,0.52,NaN,Urban
9018,8,Female,0.00,Smartphone,False,0.43,NaN,Urban
9457,10,Female,0.00,Smartphone,False,0.43,NaN,Urban
9471,9,Female,4.44,TV,True,0.50,Poor Sleep,Urban
9517,10,Female,0.00,Smartphone,False,0.53,NaN,Urban
9532,18,Male,5.98,Smartphone,True,0.49,"Poor Sleep, Eye Strain",Urban
9633,10,Male,0.00,TV,False,0.51,NaN,Urban
9641,10,Male,0.00,TV,False,0.43,NaN,Urban

In [15]:
print("Number of duplicate rows:", df.duplicated().sum())
print("Number of duplicate columns:", df.columns.duplicated().sum())

Number of duplicate rows: 44
Number of duplicate columns: 0

In [9]:
df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

Age                                    int64
Gender                                object
Avg_Daily_Screen_Time_hr             float64
Primary_Device                        object
Exceeded_Recommended_Limit              bool
Educational_to_Recreational_Ratio    float64
Health_Impacts                        object
Urban_or_Rural                        object
dtype: object

In [12]:
df.corr(numeric_only=True)

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio
Age,1.000000,0.118328,0.159173,-0.488617
Avg_Daily_Screen_Time_hr,0.118328,1.000000,0.664950,-0.087552
Exceeded_Recommended_Limit,0.159173,0.664950,1.000000,-0.126643
Educational_to_Recreational_Ratio,-0.488617,-0.087552,-0.126643,1.000000

In [10]:
Q1 = df['Avg_Daily_Screen_Time_hr'].quantile(0.25)
Q3 = df['Avg_Daily_Screen_Time_hr'].quantile(0.75)
IQR = Q3 - Q1
print("IQR:", IQR)

IQR: 1.9699999999999998